app:
  logFile: log/gin.log
  httpPort: 1080
  webSocketPort: 1089
  rpcPort: 9001
  httpUrl: 127.0.0.1:1080
  webSocketUrl:  127.0.0.1:1089

zap:
  level: info
  format: console
  prefix: '[application-notebook]'
  director: log
  link-name: latest_log
  showLine: false
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true