server:
  httpPort: 1080
  webSocketPort: 1089
  rpcPort: 9001

zap:
  level: info
  format: console
  prefix: '[application-notebook]'
  director: logs
  link-name: latest_log
  showLine: false
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
