server:
  httpPort: 1080
  webSocketPort: 1089
  rpcPort: 9001

zap:
  level: info
  format: console
  prefix: '[application-notebook]'
  director: logs
  link-name: latest_log
  showLine: false
  encode-level: LowercaseLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

redis:
  addr: localhost:6379
  password: ""
  db: 0
  poolSize: 30
  minIdleConns: 30